project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "Cubic reasoning"
  sidebar:
    style: "docked"
    border: false
    contents:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Essays
      - href: my-favourite-books.qmd
        text: My Favourite Books
      - href: about.qmd
        text: About
      - href: subscribe.qmd
        text: Subscribe
  navbar:
    style: docked
    pinned: true
    border: false
    logo: images/Logo.png
    search: true
    title: false
      

format:
  html:
    theme: cosmo
    css: styles.css
    grid:
        sidebar-width: 30%
    #    margin-width: 30%
    lang: en-GB
    include-in-header: _includes/head.html
