project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "Cubic reasoning"
  site-url: https://normansimonr.github.io/cubic_reasoning/
  description: "Thoughtful essays"
  sidebar:
    style: "docked"
    border: false
    contents:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Essays
      - href: my-favourite-books.qmd
        text: My Favourite Books
      - href: about.qmd
        text: About
      - href: subscribe.qmd
        text: Subscribe
  navbar:
    style: docked
    pinned: true
    border: false
    logo: images/Logo.png
    search: true
    title: false
  open-graph: true
  page-footer:
    center:
      - text: "© Norman Simon Rodriguez"
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/norman-r/

format:
  html:
    theme: cosmo
    css: styles.css
    grid:
        sidebar-width: 750px
        body-width: 450px
        margin-width: 750px        
        gutter-width: 3.5em
    lang: en-GB
    include-in-header: _includes/head.html
