project:
  type: website
  output-dir: docs

website:
  title: "Simon's Consultancy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Essays
      - href: my-favourite-books.qmd
        text: My Favourite Books
      - href: about.qmd
        text: About
      - href: subscribe.qmd
        text: Subscribe

format:
  html:
    theme: slate
    css: styles.css
    lang: en-GB
    include-in-header: _includes/head.html